name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ zd261998s-projects }}
  VERCEL_PROJECT_ID: ${{ kotaemon }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ cBuho7bJLlTKE9yXzos6cQT6 }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ cBuho7bJLlTKE9yXzos6cQT6 }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ cBuho7bJLlTKE9yXzos6cQT6 }}
