name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ team_yW9aOvday9Iu2mGAKl6YfGIl }}
  VERCEL_PROJECT_ID: ${{ prj_8LGV3qU372vWoiN0ExxtWhymywOS }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ VW59UyLQ7QpRARn8y6yXqrZG }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ VW59UyLQ7QpRARn8y6yXqrZG }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ VW59UyLQ7QpRARn8y6yXqrZG }}
